-- Persistent, private history for AI-generated catering images.
-- Run after supabase_auth_migration.sql and supabase_ai_image_storage_migration.sql.

create table if not exists public.ai_generated_images (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    storage_path text not null unique,
    prompt text not null,
    created_at timestamptz not null default now(),
    constraint ai_generated_images_path_owner check (
        storage_path like user_id::text || '/generated_%'
    )
);

create index if not exists idx_ai_generated_images_user_created
    on public.ai_generated_images (user_id, created_at desc);

alter table public.ai_generated_images enable row level security;

revoke all on public.ai_generated_images from public, anon;
grant select, delete on public.ai_generated_images to authenticated;
grant all on public.ai_generated_images to service_role;
grant usage, select on sequence public.ai_generated_images_id_seq to service_role;

drop policy if exists ai_generated_images_select_own on public.ai_generated_images;
create policy ai_generated_images_select_own on public.ai_generated_images
for select to authenticated
using (user_id = auth.uid());

drop policy if exists ai_generated_images_delete_own on public.ai_generated_images;
create policy ai_generated_images_delete_own on public.ai_generated_images
for delete to authenticated
using (user_id = auth.uid());
