-- Private operational error log for admin system health.
-- Run after supabase_schema.sql. Only the server service-role key may read/write events.

create table if not exists public.system_health_events (
    id bigint generated by default as identity primary key,
    component varchar(40) not null check (component in ('image_provider', 'image_storage')),
    severity varchar(16) not null default 'error' check (severity in ('warning', 'error')),
    message varchar(255) not null,
    details jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists idx_system_health_events_created_at
    on public.system_health_events (created_at desc);

alter table public.system_health_events enable row level security;
revoke all on public.system_health_events from public, anon, authenticated;
grant select, insert on public.system_health_events to service_role;
grant usage, select on sequence public.system_health_events_id_seq to service_role;