-- Customer reports and admin review queue.
-- Run after supabase_admin_migration.sql.

create table if not exists public.customer_reports (
    id bigint generated by default as identity primary key,
    customer_id bigint references public.customers(id) on delete set null,
    reporter_name varchar(150) not null,
    reporter_email varchar(150),
    target_type varchar(20) not null check (target_type in ('caterer', 'package')),
    target_name varchar(150) not null,
    caterer_id bigint references public.caterers(id) on delete set null,
    package_id bigint references public.packages(id) on delete set null,
    reason varchar(100) not null,
    details text not null check (char_length(trim(details)) between 10 and 2000),
    proof_image_path text,
    status varchar(20) not null default 'open' check (status in ('open', 'in_review', 'resolved', 'dismissed')),
    admin_note text,
    handled_by bigint references public.users(id) on delete set null,
    handled_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.customer_reports
    add column if not exists proof_image_path text;

create index if not exists idx_customer_reports_status_created
    on public.customer_reports(status, created_at desc);
create index if not exists idx_customer_reports_caterer
    on public.customer_reports(caterer_id);
create index if not exists idx_customer_reports_package
    on public.customer_reports(package_id);

create table if not exists public.customer_report_history (
    id bigint generated by default as identity primary key,
    report_id bigint not null references public.customer_reports(id) on delete cascade,
    event_type varchar(30) not null check (
        event_type in ('submitted', 'status_changed', 'admin_note_updated', 'tracking_started')
    ),
    previous_status varchar(20),
    new_status varchar(20),
    details text,
    changed_by bigint references public.users(id) on delete set null,
    created_at timestamptz not null default now()
);

create index if not exists idx_customer_report_history_report_created
    on public.customer_report_history(report_id, created_at desc);

insert into public.customer_report_history (report_id, event_type, new_status, details, created_at)
select
    r.id,
    'tracking_started',
    r.status,
    'History tracking started. Current report status: ' || replace(r.status, '_', ' '),
    r.updated_at
from public.customer_reports r
where not exists (
    select 1
    from public.customer_report_history h
    where h.report_id = r.id
);

create or replace function public.record_customer_report_history()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
    actor_id bigint;
begin
    select u.id into actor_id
    from public.users u
    where u.auth_user_id = auth.uid()
    limit 1;

    if tg_op = 'INSERT' then
        insert into public.customer_report_history (
            report_id, event_type, new_status, details, changed_by, created_at
        )
        values (
            new.id, 'submitted', new.status, 'Customer submitted a report.',
            actor_id, new.created_at
        );
        return new;
    end if;

    if old.status is distinct from new.status then
        insert into public.customer_report_history (
            report_id, event_type, previous_status, new_status, details, changed_by
        )
        values (
            new.id, 'status_changed', old.status, new.status,
            'Report marked ' || replace(new.status, '_', ' ') || '.',
            actor_id
        );
    end if;

    if old.admin_note is distinct from new.admin_note then
        insert into public.customer_report_history (
            report_id, event_type, details, changed_by
        )
        values (
            new.id, 'admin_note_updated',
            case
                when nullif(trim(new.admin_note), '') is null then 'Admin note cleared.'
                else 'Admin note: ' || new.admin_note
            end,
            actor_id
        );
    end if;

    return new;
end;
$$;

drop trigger if exists customer_reports_record_history on public.customer_reports;
create trigger customer_reports_record_history
after insert or update of status, admin_note on public.customer_reports
for each row execute function public.record_customer_report_history();

alter table public.customer_reports enable row level security;
alter table public.customer_report_history enable row level security;

drop policy if exists customer_reports_submit_own on public.customer_reports;
create policy customer_reports_submit_own on public.customer_reports
for insert to authenticated
with check (
    status = 'open'
    and admin_note is null
    and handled_by is null
    and handled_at is null
    and exists (
        select 1
        from public.customers c
        join public.users u on u.id = c.user_id
        where c.id = customer_reports.customer_id
          and u.auth_user_id = auth.uid()
    )
    and (
        (
            target_type = 'caterer'
            and package_id is null
            and exists (select 1 from public.caterers c where c.id = customer_reports.caterer_id)
        )
        or (
            target_type = 'package'
            and exists (
                select 1 from public.packages p
                where p.id = customer_reports.package_id
                  and p.caterer_id = customer_reports.caterer_id
            )
        )
    )
);

drop policy if exists customer_reports_admin_select on public.customer_reports;
create policy customer_reports_admin_select on public.customer_reports
for select to authenticated
using (public.is_admin());

drop policy if exists customer_reports_admin_update on public.customer_reports;
create policy customer_reports_admin_update on public.customer_reports
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists customer_report_history_admin_select on public.customer_report_history;
create policy customer_report_history_admin_select on public.customer_report_history
for select to authenticated
using (public.is_admin());

grant select, insert, update on public.customer_reports to authenticated;
grant usage, select on sequence public.customer_reports_id_seq to authenticated;
grant select on public.customer_report_history to authenticated;

drop trigger if exists customer_reports_set_updated_at on public.customer_reports;
create trigger customer_reports_set_updated_at
before update on public.customer_reports
for each row execute function public.set_updated_at();

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
    'customer-report-proofs',
    'customer-report-proofs',
    false,
    5242880,
    array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set public = false,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists customer_report_proofs_insert_own on storage.objects;
create policy customer_report_proofs_insert_own on storage.objects
for insert to authenticated
with check (
    bucket_id = 'customer-report-proofs'
    and (storage.foldername(name))[1] = auth.uid()::text
    and exists (
        select 1
        from public.users u
        join public.customers c on c.user_id = u.id
        where u.auth_user_id = auth.uid()
    )
);

drop policy if exists customer_report_proofs_select_own_or_admin on storage.objects;
create policy customer_report_proofs_select_own_or_admin on storage.objects
for select to authenticated
using (
    bucket_id = 'customer-report-proofs'
    and (
        (storage.foldername(name))[1] = auth.uid()::text
        or public.is_admin()
    )
);

drop policy if exists customer_report_proofs_delete_own on storage.objects;
create policy customer_report_proofs_delete_own on storage.objects
for delete to authenticated
using (
    bucket_id = 'customer-report-proofs'
    and (storage.foldername(name))[1] = auth.uid()::text
);
