-- CaterAI Supabase PostgreSQL schema
-- Schema only: existing account and transaction records are intentionally not imported.
-- Run this file in Supabase Dashboard > SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.users (
    id bigint generated by default as identity primary key,
    email varchar(100) not null unique,
    password varchar(255) not null,
    role varchar(20) not null default 'customer' check (role in ('customer', 'caterer', 'admin')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.customers (
    id bigint generated by default as identity primary key,
    user_id bigint not null unique references public.users(id) on delete cascade,
    full_name varchar(100) not null,
    phone varchar(15) not null,
    profile_picture varchar(255),
    address text,
    city varchar(50),
    is_verified boolean not null default false,
    rejection_reason text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.caterers (
    id bigint generated by default as identity primary key,
    user_id bigint not null unique references public.users(id) on delete cascade,
    business_name varchar(150) not null,
    business_permit varchar(255),
    profile_image varchar(255),
    description text,
    phone varchar(15) not null,
    address text,
    city varchar(50),
    rating numeric(3,2) not null default 0,
    paypal_email varchar(150),
    is_verified boolean not null default false,
    verification_submitted boolean not null default false,
    rejection_reason text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.packages (
    id bigint generated by default as identity primary key,
    caterer_id bigint not null references public.caterers(id) on delete cascade,
    package_name varchar(150) not null,
    description text,
    event_type varchar(50),
    price numeric(10,2) not null,
    guest_count_min integer,
    guest_count_max integer,
    includes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.package_images (
    id bigint generated by default as identity primary key,
    package_id bigint not null references public.packages(id) on delete cascade,
    image_path varchar(255) not null,
    created_at timestamptz not null default now()
);

create table if not exists public.reservations (
    id bigint generated by default as identity primary key,
    customer_id bigint not null references public.customers(id) on delete cascade,
    caterer_id bigint not null references public.caterers(id) on delete cascade,
    package_id bigint not null references public.packages(id) on delete cascade,
    event_date date not null,
    event_time time,
    event_type varchar(50),
    location text not null,
    guest_count integer not null,
    total_amount numeric(10,2) not null,
    advance_payment numeric(10,2),
    balance_amount numeric(10,2),
    payment_status varchar(20) not null default 'pending' check (payment_status in ('pending', 'partial', 'completed')),
    reservation_status varchar(20) not null default 'pending' check (reservation_status in ('pending', 'confirmed', 'completed', 'cancelled')),
    special_requests text,
    accepted_by bigint references public.users(id) on delete set null,
    accepted_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.payments (
    id bigint generated by default as identity primary key,
    reservation_id bigint not null references public.reservations(id) on delete cascade,
    amount numeric(10,2) not null,
    payment_method varchar(20) not null check (payment_method in ('e-wallet', 'cash', 'card', 'paypal')),
    payment_date date,
    reference_number varchar(100),
    receipt_image varchar(255),
    payment_status varchar(20) not null default 'pending' check (payment_status in ('pending', 'completed', 'failed')),
    provider varchar(50) default 'paypal',
    external_id varchar(100),
    webhook_payload text,
    payment_type varchar(30) default 'down_payment',
    payer_email varchar(150),
    payer_name varchar(150),
    payee_email varchar(150),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.payouts (
    id bigint generated by default as identity primary key,
    reservation_id bigint not null references public.reservations(id) on delete cascade,
    caterer_id bigint not null references public.caterers(id) on delete cascade,
    payment_id bigint unique references public.payments(id) on delete set null,
    gross_amount numeric(10,2) not null,
    platform_fee numeric(10,2) not null default 0,
    caterer_amount numeric(10,2) not null,
    payout_status varchar(20) not null default 'pending' check (payout_status in ('pending', 'processing', 'paid', 'failed')),
    payout_reference varchar(100),
    payout_batch_id varchar(100),
    payout_item_id varchar(100),
    payout_error text,
    paid_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.messages (
    id bigint generated by default as identity primary key,
    reservation_id bigint references public.reservations(id) on delete cascade,
    package_id bigint references public.packages(id) on delete set null,
    sender_id bigint not null references public.users(id) on delete cascade,
    receiver_id bigint not null references public.users(id) on delete cascade,
    message text not null,
    attachment varchar(255),
    is_read boolean not null default false,
    created_at timestamptz not null default now()
);

create table if not exists public.reviews (
    id bigint generated by default as identity primary key,
    reservation_id bigint not null references public.reservations(id) on delete cascade,
    customer_id bigint not null references public.customers(id) on delete cascade,
    caterer_id bigint not null references public.caterers(id) on delete cascade,
    rating integer check (rating between 1 and 5),
    review_text text,
    review_image varchar(255),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.recommendations (
    id bigint generated by default as identity primary key,
    customer_id bigint not null references public.customers(id) on delete cascade,
    caterer_id bigint not null references public.caterers(id) on delete cascade,
    package_id bigint not null references public.packages(id) on delete cascade,
    recommendation_score numeric(3,2),
    reason text,
    created_at timestamptz not null default now()
);

create table if not exists public.venue_visualizations (
    id bigint generated by default as identity primary key,
    reservation_id bigint not null references public.reservations(id) on delete cascade,
    original_image varchar(255) not null,
    visualized_image varchar(255),
    theme varchar(100),
    decorations text,
    created_at timestamptz not null default now()
);

create table if not exists public.webhook_events (
    id bigint generated by default as identity primary key,
    event_type varchar(100),
    payload text,
    headers text,
    reservation_id bigint references public.reservations(id) on delete set null,
    received_at timestamptz not null default now(),
    processed boolean not null default false
);

create table if not exists public.admin_activity_log (
    id bigint generated by default as identity primary key,
    admin_user_id bigint not null references public.users(id) on delete cascade,
    action varchar(80) not null,
    details varchar(255) not null,
    created_at timestamptz not null default now()
);

create index if not exists idx_user_email on public.users(email);
create index if not exists idx_caterer_user_id on public.caterers(user_id);
create index if not exists idx_package_caterer_id on public.packages(caterer_id);
create index if not exists idx_reservation_customer_id on public.reservations(customer_id);
create index if not exists idx_reservation_caterer_id on public.reservations(caterer_id);
create index if not exists idx_payment_reservation_id on public.payments(reservation_id);
create index if not exists idx_messages_sender_id on public.messages(sender_id);
create index if not exists idx_reviews_caterer_id on public.reviews(caterer_id);
create index if not exists idx_payments_external_id on public.payments(external_id);

-- Keep updated_at current when rows are modified.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at before update on public.users for each row execute function public.set_updated_at();
drop trigger if exists customers_set_updated_at on public.customers;
create trigger customers_set_updated_at before update on public.customers for each row execute function public.set_updated_at();
drop trigger if exists caterers_set_updated_at on public.caterers;
create trigger caterers_set_updated_at before update on public.caterers for each row execute function public.set_updated_at();
drop trigger if exists packages_set_updated_at on public.packages;
create trigger packages_set_updated_at before update on public.packages for each row execute function public.set_updated_at();
drop trigger if exists reservations_set_updated_at on public.reservations;
create trigger reservations_set_updated_at before update on public.reservations for each row execute function public.set_updated_at();
drop trigger if exists payments_set_updated_at on public.payments;
create trigger payments_set_updated_at before update on public.payments for each row execute function public.set_updated_at();
drop trigger if exists payouts_set_updated_at on public.payouts;
create trigger payouts_set_updated_at before update on public.payouts for each row execute function public.set_updated_at();
drop trigger if exists reviews_set_updated_at on public.reviews;
create trigger reviews_set_updated_at before update on public.reviews for each row execute function public.set_updated_at();

-- No INSERT statements are included intentionally.
