import { useState } from 'react';
import { API_BASE } from '../lib/api';
import DashboardPage from '../components/DashboardPage.jsx';

export default function AiGeneratedPhoto() {
  const [image, setImage] = useState(null); const [prompt, setPrompt] = useState('Create a polished, appetizing catering package photo with elegant food presentation and warm event styling.'); const [result, setResult] = useState(''); const [status, setStatus] = useState(''); const [loading, setLoading] = useState(false);
  async function generate(event) {
    event.preventDefault(); if (!prompt.trim()) { setStatus('Enter a description first.'); return; } if (image && !['image/jpeg', 'image/png', 'image/webp'].includes(image.type)) { setStatus('Base photo must be JPG, PNG, or WEBP.'); return; } if (image && image.size > 5 * 1024 * 1024) { setStatus('Base photo must be smaller than 5MB.'); return; }
    setLoading(true); setStatus('Generating your photo...'); setResult('');
    try { const formData = new FormData(); if (image) formData.append('image', image); formData.append('prompt', prompt); const response = await fetch(`${API_BASE}/backend/generate.php`, { method: 'POST', credentials: 'include', body: formData }); const data = await response.json(); if (!response.ok || !data.success) throw new Error(data.error || 'Photo generation failed.'); setResult(data.url); setStatus('Photo generated successfully.'); } catch (error) { setStatus(error.message); } finally { setLoading(false); }
  }
  async function downloadResult() { try { const response = await fetch(result); if (!response.ok) throw new Error('Unable to download the generated photo.'); const blob = await response.blob(); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'caterai-generated-photo.png'; link.click(); URL.revokeObjectURL(url); } catch (error) { setStatus(error.message); } }
  function resetResult() { setResult(''); setStatus(''); }
  return <DashboardPage role="caterer" section="ai-photos"><div className="ai-studio-page"><header className="ai-studio-heading"><div><p className="eyebrow">CaterAI creative studio</p><h2>What can I help you create?</h2><p>Describe an idea and turn it into a polished package visual.</p></div><span className="ai-studio-mark">✦</span></header>{status && <p className="form-alert success-alert">{status}</p>}<form className="ai-composer" onSubmit={generate}><div className="ai-composer-top"><span className="ai-composer-label">Describe your image</span><span className="ai-composer-hint">Shift + Enter for a new line</span></div><textarea aria-label="Image description" value={prompt} onChange={(event) => setPrompt(event.target.value)} placeholder="Describe a catering scene, menu, mood, or setting..." required /><div className="ai-composer-tools"><label className="ai-file-chip"><span>＋</span>{image ? image.name : 'Add optional photo'}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => { setImage(event.target.files[0] || null); setStatus(''); }} /></label><div className="ai-style-chips"><button type="button" onClick={() => setPrompt(`${prompt} editorial food photography, natural light`)}>Editorial</button><button type="button" onClick={() => setPrompt(`${prompt} warm luxury event styling`)}>Luxury</button><button type="button" onClick={() => setPrompt(`${prompt} bright outdoor celebration`)}>Outdoor</button></div><button className="ai-generate-button" disabled={loading} type="submit" aria-label="Generate image">{loading ? '...' : '↑'}</button></div></form>{result ? <section className="ai-result"><div><p className="eyebrow">Your creation</p><h3>Generated package visual</h3><div className="ai-result-actions"><button className="button button-primary" onClick={downloadResult} type="button">Download image <span>↓</span></button><button className="button ai-secondary-button" onClick={resetResult} type="button">Start over</button></div></div><img className="service-ai-preview" src={result} alt="AI generated catering preview" /></section> : <section className="ai-suggestions"><p className="eyebrow">Try an idea</p><div className="ai-suggestion-grid"><button type="button" onClick={() => setPrompt('An elegant plated dinner for a candlelit wedding reception, ivory florals, editorial food photography')}>Candlelit wedding dinner <span>↗</span></button><button type="button" onClick={() => setPrompt('A colorful tropical buffet for a relaxed outdoor birthday celebration, bright natural light')}>Tropical birthday buffet <span>↗</span></button><button type="button" onClick={() => setPrompt('A modern corporate lunch spread with refined presentation and a clean architectural venue')}>Modern corporate lunch <span>↗</span></button></div></section>}</div></DashboardPage>;
}