import { useEffect, useState } from 'react';
import { requestJson } from '../lib/api';

export default function Book() {
  const query = new URLSearchParams(window.location.search); const packageId = Number(query.get('package') || 0); const catererId = Number(query.get('caterer') || 0); const cancelled = query.get('payment') === 'cancelled'; const [status, setStatus] = useState(cancelled ? 'Payment was cancelled. Your booking was not completed.' : ''); const [loading, setLoading] = useState(false); const [item, setItem] = useState(null); const today = new Date().toISOString().split('T')[0];
  useEffect(() => { if (packageId && catererId) requestJson(`/backend/package_api.php?id=${packageId}&caterer=${catererId}`).then((data) => setItem(data.package)).catch((error) => setStatus(error.message)); }, [packageId, catererId]);
  async function submit(event) { event.preventDefault(); if (!packageId || !catererId) { setStatus('This booking link is invalid. Please choose a package first.'); return; } setLoading(true); setStatus(''); try { const values = Object.fromEntries(new FormData(event.currentTarget)); const result = await requestJson('/backend/booking_api.php', { method: 'POST', body: JSON.stringify({ ...values, package_id: packageId, caterer_id: catererId }) }); window.location.href = result.approval_url; } catch (error) { setStatus(error.message); setLoading(false); } }
  if (!packageId || !catererId) return <main className="packages-page"><nav className="packages-nav"><a className="brand" href="/">Cater<span>AI</span></a><a href="/packages">Explore caterers</a></nav><section className="packages-content booking-message"><p className="eyebrow">Booking unavailable</p><h1>{cancelled ? 'Payment cancelled.' : 'Choose a package first.'}</h1><p>{status || 'This booking link does not contain a valid package. Return to the package list and start a new booking.'}</p><a className="button button-primary" href="/packages">Explore caterers <span>↗</span></a></section></main>;
  const total = Number(item?.price || 0); const advance = total * 0.3; const balance = total - advance;
  return <main className="packages-page"><nav className="packages-nav"><a className="brand" href="/">Cater<span>AI</span></a><a href="/packages">Cancel</a></nav><section className="packages-content"><p className="eyebrow">Request your booking</p><h1>Tell us about<br /><em>your event.</em></h1><div className="booking-layout"><form className="auth-form booking-form" onSubmit={submit}>{status && <p className="form-alert error-alert">{status}</p>}<label>Event date</label><input name="event_date" type="date" min={today} required /><label>Event start time</label><input name="event_time" type="time" required /><label>Number of guests</label><input name="guest_count" type="number" min="1" required /><label>Venue name</label><input name="venue_name" placeholder="Grand Ballroom" required /><label>Venue address</label><textarea name="venue_address" placeholder="Full venue address" required /><label className="check-label"><input name="agree_terms" type="checkbox" required /> I agree to the booking terms and 30% down payment.</label><button className="button button-primary auth-submit" disabled={loading || !item} type="submit">{loading ? 'Preparing payment...' : 'Proceed to PayPal'} <span>↗</span></button></form><aside className="payment-summary"><p className="eyebrow">Payment summary</p><h2>{item?.package_name || 'Loading package...'}</h2><p className="payment-caterer">{item?.business_name || ''}</p><div className="payment-row"><span>Package total</span><strong>₱{total.toLocaleString(undefined, { minimumFractionDigits: 2 })}</strong></div><div className="payment-row advance"><span>Pay now · 30% down payment</span><strong>₱{advance.toLocaleString(undefined, { minimumFractionDigits: 2 })}</strong></div><div className="payment-row"><span>Remaining balance · 70%</span><strong>₱{balance.toLocaleString(undefined, { minimumFractionDigits: 2 })}</strong></div><p className="payment-note">You will pay the 30% down payment first through PayPal. The remaining 70% balance is paid after the caterer confirms your booking.</p></aside></div></section></main>;
}
