import { useEffect, useState } from 'react';
import { API_BASE, requestJson } from '../lib/api';

function money(value) { return `₱${Number(value || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; }

export default function Book() {
  const query = new URLSearchParams(window.location.search);
  const packageId = Number(query.get('package') || 0); const catererId = Number(query.get('caterer') || 0);
  const [status, setStatus] = useState(''); const [loading, setLoading] = useState(false); const [proofLoading, setProofLoading] = useState(false); const [item, setItem] = useState(null); const [payment, setPayment] = useState(null); const [proofSent, setProofSent] = useState(false);
  const today = new Date().toISOString().split('T')[0];
  useEffect(() => { if (packageId && catererId) requestJson(`/backend/package_api.php?id=${packageId}&caterer=${catererId}`).then((data) => setItem(data.package)).catch((error) => setStatus(error.message)); }, [packageId, catererId]);
  async function submit(event) {
    event.preventDefault(); if (!packageId || !catererId) { setStatus('This booking link is invalid. Please choose a package first.'); return; }
    setLoading(true); setStatus('');
    try { const values = Object.fromEntries(new FormData(event.currentTarget)); const result = await requestJson('/backend/booking_api.php', { method: 'POST', body: JSON.stringify({ ...values, package_id: packageId, caterer_id: catererId }) }); setPayment(result); }
    catch (error) { setStatus(error.message); setLoading(false); }
  }
  async function submitProof(event) {
    event.preventDefault(); setProofLoading(true); setStatus('');
    try { const formData = new FormData(event.currentTarget); formData.append('reservation_id', payment.reservation_id); const response = await fetch(`${API_BASE}/backend/gcash_payment_proof_api.php`, { method: 'POST', credentials: 'include', body: formData }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Unable to submit receipt.'); setProofSent(true); setStatus(result.message); }
    catch (error) { setStatus(error.message); } finally { setProofLoading(false); }
  }
  useEffect(() => {
    if (!payment) return undefined;
    const closeOnEscape = (event) => { if (event.key === 'Escape' && proofSent) setPayment(null); };
    document.addEventListener('keydown', closeOnEscape);
    return () => document.removeEventListener('keydown', closeOnEscape);
  }, [payment, proofSent]);
  if (!packageId || !catererId) return <main className="packages-page"><nav className="packages-nav"><a className="brand" href="/">Cater<span>AI</span></a><a href="/packages">Explore caterers</a></nav><section className="packages-content booking-message"><p className="eyebrow">Booking unavailable</p><h1>Choose a package first.</h1><p>{status || 'This booking link does not contain a valid package.'}</p><a className="button button-primary" href="/packages">Explore caterers <span>↗</span></a></section></main>;
  if (payment) return <main className="packages-page"><nav className="packages-nav"><a className="brand" href="/">Cater<span>AI</span></a><a href="/dashboard/customer">My dashboard</a></nav><section className="packages-content booking-message"><p className="eyebrow">Booking request</p><h1>Booking created.</h1><p>Your booking is waiting for GCash payment verification.</p></section><div className="gcash-modal-backdrop" role="presentation"><section aria-labelledby="gcash-modal-title" aria-modal="true" className="gcash-modal" role="dialog"><div className="gcash-modal-header"><div><p className="eyebrow">GCash payment</p><h1 id="gcash-modal-title">Complete your down payment.</h1></div>{proofSent && <button aria-label="Close payment dialog" className="gcash-modal-close" onClick={() => setPayment(null)} type="button">×</button>}</div><p>Scan the QR code and pay <strong>{money(payment.amount)}</strong>. Then upload your GCash receipt and reference number so the caterer can verify the payment.</p><img className="gcash-qr-preview booking-qr" src={`${API_BASE}${payment.gcash_qr_code}`} alt="Caterer GCash payment QR code" />{status && <p className="form-alert success-alert">{status}</p>}{!proofSent && <form className="auth-form gcash-proof-form" onSubmit={submitProof}><label>GCash reference number<input name="reference_number" required placeholder="e.g. 1234567890" /></label><label>Payment receipt<input name="receipt_image" type="file" accept="image/jpeg,image/png,image/webp" required /></label><button className="button button-primary" disabled={proofLoading} type="submit">{proofLoading ? 'Submitting receipt...' : 'Submit payment receipt'} <span>↗</span></button></form>}{proofSent && <div className="gcash-modal-complete"><p>Reservation #{payment.reservation_id} is waiting for caterer payment verification.</p><a className="button button-primary" href="/dashboard/customer">Go to my dashboard <span>↗</span></a></div>}</section></div></main>;
  const total = Number(item?.price || 0); const advance = total * 0.3; const balance = total - advance;
  return <main className="packages-page"><nav className="packages-nav"><a className="brand" href="/">Cater<span>AI</span></a><a href="/packages">Cancel</a></nav><section className="packages-content"><p className="eyebrow">Request your booking</p><h1>Tell us about<br /><em>your event.</em></h1><div className="booking-layout"><form className="auth-form booking-form" onSubmit={submit}>{status && <p className="form-alert error-alert">{status}</p>}<label>Event date</label><input name="event_date" type="date" min={today} required /><label>Event start time</label><input name="event_time" type="time" required /><label>Number of guests</label><input name="guest_count" type="number" min="1" required /><label>Venue name</label><input name="venue_name" placeholder="Grand Ballroom" required /><label>Venue address</label><textarea name="venue_address" placeholder="Full venue address" required /><label className="check-label"><input name="agree_terms" type="checkbox" required /> I agree to the booking terms and 30% down payment.</label><button className="button button-primary auth-submit" disabled={loading || !item} type="submit">{loading ? 'Preparing GCash payment...' : 'Continue to GCash'} <span>↗</span></button></form><aside className="payment-summary"><p className="eyebrow">GCash payment summary</p><h2>{item?.package_name || 'Loading package...'}</h2><p className="payment-caterer">{item?.business_name || ''}</p><div className="payment-row"><span>Package total</span><strong>{money(total)}</strong></div><div className="payment-row advance"><span>Pay now · 30% down payment</span><strong>{money(advance)}</strong></div><div className="payment-row"><span>Remaining balance · 70%</span><strong>{money(balance)}</strong></div><p className="payment-note">After submitting your booking, scan the caterer&apos;s GCash QR code and upload the receipt.</p></aside></div></section></main>;
}
