import { useEffect, useState } from 'react';
import { API_BASE, requestJson } from '../lib/api';
import DashboardPage from '../components/DashboardPage.jsx';

export default function CatererProfile() {
  const [profile, setProfile] = useState(null); const [status, setStatus] = useState(''); const [error, setError] = useState('');
  const load = () => requestJson('/backend/dashboard_api.php?action=caterer_profile').then((data) => setProfile(data.caterer)).catch((reason) => setError(reason.message));
  useEffect(() => { load(); }, []);
  async function update(event) { event.preventDefault(); setStatus(''); setError(''); try { await requestJson('/backend/dashboard_api.php?action=update_profile', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); setStatus('Profile updated successfully.'); load(); } catch (reason) { setError(reason.message); } }
  async function upload(event) { const data = new FormData(); data.append('business_permit', event.target.files[0]); try { const response = await fetch(`${API_BASE}/backend/permit_upload_api.php`, { method: 'POST', credentials: 'include', body: data }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setStatus('Business permit uploaded.'); load(); } catch (reason) { setError(reason.message); } }
  async function submitVerification() { try { await requestJson('/backend/dashboard_api.php?action=submit_verification', { method: 'POST', body: '{}' }); setStatus('Verification submitted for admin review.'); load(); } catch (reason) { setError(reason.message); } }
  if (!profile) return <DashboardPage role="caterer" section="profile"><p>{error || 'Loading profile...'}</p></DashboardPage>;
  return <DashboardPage role="caterer" section="profile"><>{status && <p className="form-alert success-alert">{status}</p>}{error && <p className="form-alert error-alert">{error}</p>}<form className="profile-form" onSubmit={update}><label>Business name<input name="business_name" defaultValue={profile.business_name} required /></label><label>Phone<input name="phone" defaultValue={profile.phone || ''} required /></label><label>Address<input name="address" defaultValue={profile.address || ''} required /></label><label>City<input name="city" defaultValue={profile.city || ''} required /></label><label>Description<textarea name="description" defaultValue={profile.description || ''} /></label><label>PayPal email<input name="paypal_email" type="email" defaultValue={profile.paypal_email || ''} /></label><button className="button button-primary" type="submit">Save profile</button></form><div className="verification-panel"><h3>Account verification</h3><p>Status: {profile.is_verified ? 'Verified' : profile.verification_submitted ? 'Pending admin review' : 'Not submitted'}</p><input type="file" accept="application/pdf,image/jpeg,image/png" onChange={upload} /><button className="button button-primary" disabled={!profile.business_permit || profile.verification_submitted} onClick={submitVerification} type="button">Submit for verification</button></div></></DashboardPage>;
}
