import { useEffect, useState } from 'react';
import { requestJson } from '../lib/api';
import DashboardPage from '../components/DashboardPage.jsx';

const initialForm = { package_name: '', event_type: '', guest_range: '', price: '', max_bookings: '', description: '', features: '' };

export default function ManageServices() {
  const [services, setServices] = useState([]); const [form, setForm] = useState(initialForm); const [images, setImages] = useState([]); const [editingId, setEditingId] = useState(null); const [status, setStatus] = useState('');
  const load = () => requestJson('/backend/dashboard_api.php?action=services').then((data) => setServices(data.services || [])).catch((error) => setStatus(error.message));
  useEffect(() => { load(); }, []);
  async function create(event) { event.preventDefault(); try { const data = await requestJson(`/backend/dashboard_api.php?action=${editingId ? 'update_service' : 'create_service'}`, { method: 'POST', body: JSON.stringify({ ...form, package_id: editingId }) }); const packageId = editingId || data.package_id; if (images.length && packageId) { const upload = new FormData(); upload.append('package_id', packageId); images.forEach((image) => upload.append('images[]', image)); await requestJson('/backend/package_images_api.php', { method: 'POST', body: upload }); } setForm(initialForm); setImages([]); setEditingId(null); setStatus(editingId ? 'Service updated.' : 'Service created.'); load(); } catch (error) { setStatus(error.message); } }
  async function remove(id) { try { await requestJson('/backend/dashboard_api.php?action=delete_service', { method: 'POST', body: JSON.stringify({ package_id: id }) }); setStatus('Service deleted.'); load(); } catch (error) { setStatus(error.message); } }
  function edit(service) { setEditingId(service.id); setImages([]); setForm({ package_name: service.package_name, event_type: service.event_type, guest_range: `${service.guest_count_min}-${service.guest_count_max}`, price: service.price, max_bookings: service.max_bookings || '', description: service.description || '', features: service.includes || '' }); }
  const fields = [['package_name', 'Package name'], ['event_type', 'Event type'], ['guest_range', 'Guest range, e.g. 50-100'], ['price', 'Price'], ['max_bookings', 'Maximum bookings, 0 means unlimited']];
  return <DashboardPage role="caterer" section="services"><div className="services-workspace">
    {status && <p className="form-alert success-alert">{status}</p>}
    <div className="services-heading"><div><h2>Manage your packages</h2><p>Create clear, complete offers that customers can compare easily.</p></div><span className="services-count">{services.length} package{services.length === 1 ? '' : 's'}</span></div>
    <div className="services-layout">
      <form className="profile-form service-form" onSubmit={create}>
        <div className="service-form-heading"><div><p className="eyebrow">{editingId ? 'Edit package' : 'New package'}</p><h3>{editingId ? 'Update service package' : 'Add service package'}</h3></div>{editingId && <button className="service-cancel" onClick={() => { setEditingId(null); setForm(initialForm); setImages([]); }} type="button">Cancel</button>}</div>
        <fieldset><legend>Package details</legend><div className="service-fields">{fields.slice(0, 2).map(([name, label]) => <label key={name}>{label}<input name={name} type="text" value={form[name]} onChange={(event) => setForm({ ...form, [name]: event.target.value })} required /></label>)}</div></fieldset>
        <fieldset><legend>Capacity and pricing</legend><div className="service-fields service-fields-three">{fields.slice(2).map(([name, label]) => <label key={name}>{label}<input name={name} type={name === 'price' || name === 'max_bookings' ? 'number' : 'text'} min={name === 'max_bookings' ? '0' : undefined} value={form[name]} onChange={(event) => setForm({ ...form, [name]: event.target.value })} required={name !== 'max_bookings'} /></label>)}</div></fieldset>
        <fieldset><legend>Presentation</legend><div className="service-fields"><label>Description<textarea name="description" value={form.description} onChange={(event) => setForm({ ...form, [event.target.name]: event.target.value })} /></label><label>Includes<textarea name="features" value={form.features} onChange={(event) => setForm({ ...form, [event.target.name]: event.target.value })} /></label></div><label className="service-upload">Sample photos<input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={(event) => setImages(Array.from(event.target.files || []))} /><small>Upload photos of your setup, food presentation, or sample designs.</small></label>{images.length > 0 && <p className="service-selection">{images.length} photo{images.length === 1 ? '' : 's'} selected.</p>}</fieldset>
        <button className="button button-primary service-submit" type="submit">{editingId ? 'Update service' : 'Create service'} <span>↗</span></button>
      </form>
      <section className="services-catalog"><div className="catalog-heading"><div><p className="eyebrow">Your catalog</p><h3>Created packages</h3></div><span>Manage availability and details</span></div>{services.length === 0 ? <p className="service-empty">No packages yet. Your created packages will appear here.</p> : <div className="service-list">{services.map((service) => <article className="package-card service-card" key={service.id}><div className="service-card-top"><div><span className="service-type">{service.event_type}</span><h3>{service.package_name}</h3></div><strong>₱{Number(service.price).toLocaleString()}</strong></div><div className="service-card-meta"><span><b>{service.guest_count_min}-{service.guest_count_max}</b> guests</span><span><b>{service.max_bookings > 0 ? `${service.booking_count}/${service.max_bookings}` : 'Unlimited'}</b> bookings</span></div>{service.description && <p className="service-description">{service.description}</p>}{service.max_bookings > 0 && Number(service.booking_count) >= Number(service.max_bookings) && <strong className="package-full-label">Package full</strong>}<div className="service-actions"><button className="button service-edit" onClick={() => edit(service)} type="button">Edit package</button><button className="button service-delete" onClick={() => remove(service.id)} type="button">Delete</button></div></article>)}</div>}</section>
    </div>
  </div></DashboardPage>;
}
